### ISSUE TITLE
Because of change network interface in launch template i got these error

### ISSUE THREAD

**Issue by hussein-mimi** [cloudacademy/terraform-aws#1]
Hello
in this excercise i found error, i gor error while apply terraform that decurity groups must be attached in network interface while network_interface is used. 

this is the error
│ Error: Error creating Auto Scaling Group: InvalidQueryParameter: Invalid launch template: When a network interface is provided, the security groups must be a part of it.
│ 	status code: 400, request id: da0c1dc6-c7fa-4a9d-912a-852cfc1f656f
│
│   with aws_autoscaling_group.asg,
│   on main.tf line 297, in resource "aws_autoscaling_group" "asg":
│  297: resource "aws_autoscaling_group" "asg" {
│

and the solution was remove vpc_security_groups_ids and make it like it was in video

**Comment by lrakai** [comment]
Thank you for reporting the issue and proposing a solution!  We will investigate and repair the lab.

**Comment by jeremycook123** [comment]
This has now been fixed.

Note: the correct fix involves removing the redundant **network_interfaces** block - which isn't required since it was only stating that the instance shouldn't have a public IP address auto-assigned - this is implicitly the case, that is by default the instance will **not** have a public IP address auto-assigned. **vpc_security_groups_ids** must remain as it sets the security group/s to be attached to the instance.

Updated aws_launch_template:
```
resource "aws_launch_template" "launchtemplate1" {
  name = "web"

  image_id               = data.aws_ami.ubuntu.id
  instance_type          = var.instance_type
  key_name               = var.key_name
  vpc_security_group_ids = [aws_security_group.webserver.id]

  tag_specifications {
    resource_type = "instance"

    tags = {
      Name = "WebServer"
    }
  }

  user_data = filebase64("${path.module}/ec2.userdata")
}
```
